spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/inventario
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate

    show-sql: true

  flyway:
    enabled: true

server:
  port: 8080